### ISSUE TITLE
Remove branch add-intro

### ISSUE THREAD

**Issue by eugenepeh** [se-edu/samplerepo-pr-practice#4]
One student on slack had no idea what's going on when this happened.

![image](https://user-images.githubusercontent.com/19277206/35924066-f7bb9e2e-0c5c-11e8-9314-a05b42a9fcab.png)

This has occurred due to him created a local branch with the same name as existing remote branch.

**Comment by damithc** [comment]
Do we ask students to use that name, or pure coincidence?

**Comment by eugenepeh** [comment]
Yes, the instruction on website is to use that name.
Under week 4.7c

![image](https://user-images.githubusercontent.com/19277206/35976251-87372560-0d1a-11e8-834c-bc41781bdee6.png)

Not sure if this is meant to be part of the learning outcome. Also `add-intro` branch is 2 commits ahead of `master` branch.

**Comment by damithc** [comment]
Branch deleted from this repo as well as semester repo
